// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpGVEcQ8GeWHJRMP9m1FXQuIwrH-hV1XA',
    appId: '1:275636489907:web:9c32783209327c615caac6',
    messagingSenderId: '275636489907',
    projectId: 'ingrdnts-f505f',
    authDomain: 'ingrdnts-f505f.firebaseapp.com',
    storageBucket: 'ingrdnts-f505f.firebasestorage.app',
    measurementId: 'G-FHWEZMVNK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1apwu9bveG4eI3d1-pJ1-Vtx2Wnd2S1w',
    appId: '1:275636489907:android:2496b7a8a11805dc5caac6',
    messagingSenderId: '275636489907',
    projectId: 'ingrdnts-f505f',
    storageBucket: 'ingrdnts-f505f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaxdRPn9iH2ynQLkmhI-_OtfOhot2gynw',
    appId: '1:275636489907:ios:0d33545658e3be845caac6',
    messagingSenderId: '275636489907',
    projectId: 'ingrdnts-f505f',
    storageBucket: 'ingrdnts-f505f.firebasestorage.app',
    iosBundleId: 'com.example.finalProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaxdRPn9iH2ynQLkmhI-_OtfOhot2gynw',
    appId: '1:275636489907:ios:0d33545658e3be845caac6',
    messagingSenderId: '275636489907',
    projectId: 'ingrdnts-f505f',
    storageBucket: 'ingrdnts-f505f.firebasestorage.app',
    iosBundleId: 'com.example.finalProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpGVEcQ8GeWHJRMP9m1FXQuIwrH-hV1XA',
    appId: '1:275636489907:web:9e8b63d9b0d9c8d35caac6',
    messagingSenderId: '275636489907',
    projectId: 'ingrdnts-f505f',
    authDomain: 'ingrdnts-f505f.firebaseapp.com',
    storageBucket: 'ingrdnts-f505f.firebasestorage.app',
    measurementId: 'G-4SLY4KEM02',
  );
}
